In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('Chocolate-Sales.csv')
data

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04-Jan-22,"$5,320",180
1,Van Tuxwell,India,85% Dark Bars,01-Aug-22,"$7,896",94
2,Gigi Bohling,India,Peanut Butter Cubes,07-Jul-22,"$4,501",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27-Apr-22,"$12,726",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24-Feb-22,"$13,685",184
...,...,...,...,...,...,...
1089,Karlen McCaffrey,Australia,Spicy Special Slims,17-May-22,"$4,410",323
1090,Jehu Rudeforth,USA,White Choc,07-Jun-22,"$6,559",119
1091,Ches Bonnell,Canada,Organic Choco Syrup,26-Jul-22,$574,217
1092,Dotty Strutley,India,Eclairs,28-Jul-22,"$2,086",384
1093,Karlen McCaffrey,India,70% Dark Bites,23-May-22,"$5,075",344

In [3]:
# renomabrando los encabezados 
data = data.rename(columns={
    "Sales Person" : "Vendedor",
    "Country" : "Pais",
    "Product" : "Productos",
    "Date" : "Fecha",
    "Amount" : "Monto",
    "Boxes Shipped" : "Cajas_enviadas"
})
data.head()

,Vendedor,Pais,Productos,Fecha,Monto,Cajas_enviadas
0,Jehu Rudeforth,UK,Mint Chip Choco,04-Jan-22,"$5,320",180
1,Van Tuxwell,India,85% Dark Bars,01-Aug-22,"$7,896",94
2,Gigi Bohling,India,Peanut Butter Cubes,07-Jul-22,"$4,501",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27-Apr-22,"$12,726",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24-Feb-22,"$13,685",184

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1094 entries, 0 to 1093
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Vendedor        1094 non-null   object
 1   Pais            1094 non-null   object
 2   Productos       1094 non-null   object
 3   Fecha           1094 non-null   object
 4   Monto           1094 non-null   object
 5   Cajas_enviadas  1094 non-null   int64
dtypes: int64(1), object(5)
memory usage: 51.4+ KB

In [15]:
print(data['Monto'].dtype)
print(data['Monto'].head())

float64
0     5320.0
1     7896.0
2     4501.0
3    12726.0
4    13685.0
Name: Monto, dtype: float64

In [16]:
# quitamos el $ del monto
data['Monto'] = data['Monto'].replace('$', '', regex=False).replace(',', '').astype(float)
data['Fecha'] = pd.to_datetime(data['Fecha'], format='%d-%b-%y')

In [17]:
data

,Vendedor,Pais,Productos,Fecha,Monto,Cajas_enviadas
0,Jehu Rudeforth,UK,Mint Chip Choco,2022-01-04,5320.0,180
1,Van Tuxwell,India,85% Dark Bars,2022-08-01,7896.0,94
2,Gigi Bohling,India,Peanut Butter Cubes,2022-07-07,4501.0,91
3,Jan Morforth,Australia,Peanut Butter Cubes,2022-04-27,12726.0,342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,2022-02-24,13685.0,184
...,...,...,...,...,...,...
1089,Karlen McCaffrey,Australia,Spicy Special Slims,2022-05-17,4410.0,323
1090,Jehu Rudeforth,USA,White Choc,2022-06-07,6559.0,119
1091,Ches Bonnell,Canada,Organic Choco Syrup,2022-07-26,574.0,217
1092,Dotty Strutley,India,Eclairs,2022-07-28,2086.0,384
1093,Karlen McCaffrey,India,70% Dark Bites,2022-05-23,5075.0,344

In [24]:
print(data.isnull().sum()) # datos faltantes
print("-------------------")
print(data.duplicated().sum()) # valores faltantes

Vendedor          0
Pais              0
Productos         0
Fecha             0
Monto             0
Cajas_enviadas    0
dtype: int64
-------------------
0

In [27]:
print(data["Vendedor"].unique())
print("---------------------------------------------------------------")
print(data["Productos"].unique())
print("---------------------------------------------------------------")
print(data["Pais"].unique())

['Jehu Rudeforth' 'Van Tuxwell' 'Gigi Bohling' 'Jan Morforth' 'Oby Sorrel'
 'Gunar Cockshoot' 'Brien Boise' 'Rafaelita Blaksland' 'Barr Faughny'
 'Mallorie Waber' 'Karlen McCaffrey' "Marney O'Breen" 'Beverie Moffet'
 'Roddy Speechley' 'Curtice Advani' 'Husein Augar' 'Kaine Padly'
 'Dennison Crosswaite' "Wilone O'Kielt" 'Andria Kimpton' 'Kelci Walkden'
 'Camilla Castle' 'Madelene Upcott' 'Dotty Strutley' 'Ches Bonnell']
---------------------------------------------------------------
['Mint Chip Choco' '85% Dark Bars' 'Peanut Butter Cubes'
 'Smooth Sliky Salty' '99% Dark & Pure' 'After Nines' '50% Dark Bites'
 'Orange Choco' 'Eclairs' 'Drinking Coco' 'Organic Choco Syrup'
 'Milk Bars' 'Spicy Special Slims' 'Fruit & Nut Bars' 'White Choc'
 'Manuka Honey Choco' 'Almond Choco' 'Raspberry Choco'
 'Choco Coated Almonds' "Baker's Choco Chips" 'Caramel Stuffed Bars'
 '70% Dark Bites']
---------------------------------------------------------------
['UK' 'India' 'Australia' 'New Zealand' 'USA' 'Canada']

In [29]:
data["Productos"].value_counts()

Productos
Eclairs                 60
50% Dark Bites          60
Smooth Sliky Salty      59
White Choc              58
Drinking Coco           56
Spicy Special Slims     54
Organic Choco Syrup     52
85% Dark Bars           50
Fruit & Nut Bars        50
After Nines             50
Peanut Butter Cubes     49
99% Dark & Pure         49
Milk Bars               49
Raspberry Choco         48
Almond Choco            48
Orange Choco            47
Mint Chip Choco         45
Manuka Honey Choco      45
Caramel Stuffed Bars    43
70% Dark Bites          42
Baker's Choco Chips     41
Choco Coated Almonds    39
Name: count, dtype: int64